# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address_Book', '0003_auto_20170621_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='flat_number',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
