# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address_Book', '0006_auto_20170622_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
